inicio:
    pattern:  /
    defaults: { _controller: UpaoFundoBundle:Principal:index }

upao_fundo_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: UpaoFundoBundle:Default:index }

abono:
    resource: "@UpaoFundoBundle/Resources/config/routing/abono.yml"
    prefix:   /abono

abonoplanta:
    resource: "@UpaoFundoBundle/Resources/config/routing/abonoplanta.yml"
    prefix:   /abonoplanta

cliente:
    resource: "@UpaoFundoBundle/Resources/config/routing/cliente.yml"
    prefix:   /cliente

cosecha:
    resource: "@UpaoFundoBundle/Resources/config/routing/cosecha.yml"
    prefix:   /cosecha

cosechaplanta:
    resource: "@UpaoFundoBundle/Resources/config/routing/cosechaplanta.yml"
    prefix:   /cosechaplanta

empleado:
    resource: "@UpaoFundoBundle/Resources/config/routing/empleado.yml"
    prefix:   /empleado

estadoambiente:
    resource: "@UpaoFundoBundle/Resources/config/routing/estadoambiente.yml"
    prefix:   /estadoambiente

fumigacion:
    resource: "@UpaoFundoBundle/Resources/config/routing/fumigacion.yml"
    prefix:   /fumigacion

fumigacionplanta:
    resource: "@UpaoFundoBundle/Resources/config/routing/fumigacionplanta.yml"
    prefix:   /fumigacionplanta

pedido:
    resource: "@UpaoFundoBundle/Resources/config/routing/pedido.yml"
    prefix:   /pedido

planta:
    resource: "@UpaoFundoBundle/Resources/config/routing/planta.yml"
    prefix:   /planta

problema:
    resource: "@UpaoFundoBundle/Resources/config/routing/problema.yml"
    prefix:   /problema

proveedor:
    resource: "@UpaoFundoBundle/Resources/config/routing/proveedor.yml"
    prefix:   /proveedor

tipoplanta:
    resource: "@UpaoFundoBundle/Resources/config/routing/tipoplanta.yml"
    prefix:   /tipoplanta

venta:
    resource: "@UpaoFundoBundle/Resources/config/routing/venta.yml"
    prefix:   /venta

