parameters:
#    upao_fundo.example.class: Upao\FundoBundle\Example

services:
    fundo.twig.fundo_extension:
        class: Upao\FundoBundle\Twig\FundoExtension
        arguments: [@service_container]
        tags:
            - { name: twig.extension }
#    upao_fundo.example:
#        class: %upao_fundo.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
