parameters:
#    upao_fundo.example.class: Upao\FundoBundle\Example

services:
#    upao_fundo.example:
#        class: %upao_fundo.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
